basePath: /
definitions:
  handler.signInInput:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  models.Airport:
    properties:
      city:
        type: string
      code:
        type: string
      country:
        type: string
      machine_location:
        type: string
    type: object
  models.Currency:
    properties:
      code:
        type: string
      rate_to_usd:
        type: number
    type: object
  models.Exchange:
    properties:
      acceptor_approve:
        type: boolean
      acceptor_code:
        type: string
      acceptor_id:
        type: integer
      author_approve:
        type: boolean
      author_code:
        type: string
      author_id:
        type: integer
      expired_time:
        type: string
      id:
        type: integer
      request:
        $ref: '#/definitions/models.Request'
      status:
        type: string
    type: object
  models.GetRequestsData:
    properties:
      airport:
        type: string
      date_time:
        type: string
      from:
        type: string
      to:
        type: string
      value:
        type: number
    required:
    - airport
    - date_time
    - from
    - to
    - value
    type: object
  models.IdRequest:
    properties:
      id:
        type: integer
    type: object
  models.Request:
    properties:
      airport:
        $ref: '#/definitions/models.Airport'
      author_id:
        type: integer
      date_time:
        type: string
      from_currency:
        $ref: '#/definitions/models.Currency'
      id:
        type: integer
      to_currency:
        $ref: '#/definitions/models.Currency'
      value_from:
        type: number
      value_to:
        type: number
    type: object
  models.User:
    properties:
      login:
        type: string
      name:
        type: string
      password:
        type: string
      rating:
        type: number
      surname:
        type: string
    required:
    - login
    - name
    - password
    - surname
    type: object
  models.errorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Exchange app
  title: Exchange app
  version: "1.0"
paths:
  /api/airports:
    get:
      consumes:
      - application/json
      description: get airports
      operationId: get-airports
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetAirports
      tags:
      - api
  /api/currencies:
    get:
      consumes:
      - application/json
      description: get currencies
      operationId: get-currencies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetCurrencies
      tags:
      - api
  /api/exchanges:
    get:
      consumes:
      - application/json
      description: get user's exchanges
      operationId: get-users-exchange
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetUsersExchanges
      tags:
      - api
    post:
      consumes:
      - application/json
      description: create exchange
      operationId: create-exchange
      parameters:
      - description: exchange info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Exchange'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: CreateExchange
      tags:
      - api
  /api/exchanges/accept:
    post:
      consumes:
      - application/json
      description: accept exchange
      operationId: accept-exchange
      parameters:
      - description: exchange id
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.IdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: AcceptExchange
      tags:
      - api
  /api/exchanges/by-id:
    post:
      consumes:
      - application/json
      description: get exchange by id
      operationId: get-exchange
      parameters:
      - description: exchange id
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.IdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetExchange
      tags:
      - api
  /api/exchanges/decline:
    post:
      consumes:
      - application/json
      description: decline exchange
      operationId: decline-exchange
      parameters:
      - description: exchange id
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.IdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: DeclineExchange
      tags:
      - api
  /api/requests:
    post:
      consumes:
      - application/json
      description: create new request for exchange
      operationId: create-request
      parameters:
      - description: request info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: CreateRequest
      tags:
      - api
  /api/requests/get-all:
    post:
      consumes:
      - application/json
      description: get all request by specified params
      operationId: get-requests
      parameters:
      - description: request info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.GetRequestsData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetRequests
      tags:
      - api
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login
      operationId: login
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.errorResponse'
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create new user account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.errorResponse'
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
